version: '2'

services:
  rocketchat:
    image: mtro/docker-rc:latest
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://10.10.30.52:27017/rocketchat
      #- MONGO_OPLOG_URL=mongodb://10.10.30.52:27017/local
    ports:
      - 5001:3000
